name: Run Actionlint
on: 
  pull_request:
    branches: main
    
jobs:
  run-actionlint:
    runs-on: ubuntu-latest
    permissions:
      # needed for the checkout action
      contents: read
      # needed to annotate the files in a pull request with comments
      pull-requests: write
    steps: 
    # checkout the source code to analyze
    - uses: actions/checkout@v4 # v3

    # run the actionlinter
    - uses: devops-actions/actionlint@c0ee017f8abef55d843a647cd737b87a1976eb69 # v0.1.1 
      # trying to find a way to fail the workflow, but not block the PR, so far no luck with required workflows
      #continue-on-error: true
      
    #- if: failure()
    #  run: echo "here"    
