name: Run Actionlint
on: 
  pull_request:
    branches: main
    
jobs:
  run-actionlint:
    runs-on: ubuntu-latest
    permissions:
      # needed for the checkout action
      contents: read
      # needed to annotate the files in a pull request with comments
      pull-requests: write
    steps: 
    # checkout the source code to analyze
    - uses: actions/checkout@v3 # v3

    # run the actionlinter, will fail on errors
    - uses: devops-actions/actionlint@v0.1.0 
    
