name: "Approve Dependabot PR's" 
on:
  workflow_dispatch:
  pull_request:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
  
permissions:
  contents: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Get correct token to use
        id: get-token
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # shell script to use either secrets.GH_TOKEN or secrets.GITHUB_TOKEN depending on which is set
          if [[] $GH_TOKEN ]]; then
            echo "token=$GH_TOKEN" > GITHUB_OUTPUT
          else 
            echo "token=$GITHUB_TOKEN" > GITHUB_OUTPUT
          fi

      - name: Load Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@4de7a6c08ce727a42e0adbbdc345f761a01240ce #v1.3.6
        with:
          github-token: ${{ steps.get-token.outputs.token }}
      
      - name: Approve the PR
        if:  steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
      
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
