name: self-hosted
on:
  workflow_dispatch:
  push:
    paths: 
      - .github/workflows/self-hosted.yml
jobs:
  self-hosted-number1:
    runs-on: self-hosted
    steps:
       - uses: actions/checkout@v2
       - run: echo "Hello world"
       
       - name: Checkout Git repo manually
         run: |
           mkdir npm-cli
           cd npm-cli
           git clone https://github.com/npm/cli.git

       - run: dotnet --version

       - run: npm version
