name: self-hosted
on:
  workflow_dispatch:
  push:
    paths: 
      - .github/workflows/self-hosted.yml
jobs:
  self-hosted-number1:
    runs-on: self-hosted
    steps:
       - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
       - run: echo "Hello world"
       
       - name: Checkout Git repo manually
         run: |
           mkdir my-repo
           cd my-repo
           git clone https://github.com/devops-actions/.github.git

       - run: dotnet --version

       - run: npm version
