name: Time for new release

on:
  workflow_call:
  
jobs:
  check-time-for-new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # we need all tags
      
      - shell: pwsh
        id: needs-release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # get latest release and the tag from it
          $release = gh api 'repos/{owner}/{repo}/releases/latest' | ConvertFrom-Json
          $tag = $release.tag_name
          
          # get the information from the last tag (assuming that is latest!)
          $info = git describe --tags
          $commitsSinceLastTag = $info.Split("-")[1]
          
          if ($commitsSinceLastTag -gt 0) {
            Write-Host "Found [$commitsSinceLastTag] commits since last tag, we should create a release"
            echo "newrelease=true" >> $env:GITHUB_OUTPUT
          }
          else {
            Write-Host "No changes since last tag, so nothing to release"
            echo "newrelease=false" >> $env:GITHUB_OUTPUT
          }
          
      # todo: 
      # set-output in needs-release
      # check needs-release in new step
      - run: echo "${{ steps.needs-release.outputs.newrelease }}"
      
      - name: Show output
        if: ${{ steps.needs-release.outputs.newrelease === "true"
        run: echo "Hi there"
      
      # if yes, call the api to create a new release
      # fetch new release tag first (sem ver? or do we need to check if we made breaking changes? Should not be breaking if all it is, are dependency updates?
